### ISSUE TITLE
Feature: display totals

### ISSUE THREAD

**Issue by atorger** [matthiasfeist/nvdb2osm-pipeline#1]
Wouldn't it be cool to display the total amount of megabytes of OSM files for whole Sweden plus the total amount done? So one can immediately get a (depressing) view of how much work is left :-)

**Comment by matthiasfeist** [comment]
Haha. very depressing metric indeed. I'll look into it :)

**Comment by matthiasfeist** [comment]
Done. Let me know what you think :)

**Comment by atorger** [comment]
It looks great! And depressing...

**Comment by matthiasfeist** [comment]
yes indeed 😢
