### ISSUE TITLE
Feature: download link to shape.zip for failed runs

### ISSUE THREAD

**Issue by atorger** [matthiasfeist/nvdb2osm-pipeline#2]
As it's quite messy to make input files nowadays, one need to split them first, it would simplify a bit for debugging if the failed runs in addition of the log file also made the source shape zip file available for download so I can run the script and provoke the error locally for debugging without having to generate the input file first.

**Comment by matthiasfeist** [comment]
shouldn't be too hard... let me check

**Comment by matthiasfeist** [comment]
I'm testing the upload: commit a1770da4c73a551f45fb812c3373ac6935b2b820

**Comment by matthiasfeist** [comment]
OK it works. I am not exposing the files on the HTML page but you can get it on the same host.

Example: https://nvdb-osm-map-data.s3.eu-north-1.amazonaws.com/shp/Nacka.zip
The log of the split operation is here: https://nvdb-osm-map-data.s3.eu-north-1.amazonaws.com/shp/split_1.log (named by the "länskod")

It's gonna take probably around 1 day until all files are processed so some URLs you try might result in a 404. But tomorrow by this time everything should be available.
